## Антонов Матвей БПМ201

#### Лабораторная работа 5

#### Вариант 2 (5.1.2, 5.2, 5.7.1)

In [1]:
import matplotlib.pyplot as plt
import numpy as np

Дана система уравнений $Ax=b$. Найти решение системы с помощью метода Гаусса. Выполнить 10 итераций по методу Зейделя. Принимая решение, полученное с помощью метода Гаусса за точное, найти величину абсолютной погрешности итерационного решения.

ПОРЯДОК РЕШЕНИЯ ЗАДАЧИ:
1. Задать матрицу системы A и вектор правой части b. Используя встроенную функцию lsolve пакета MATHCAD (или другие встроенные функции в wolfram mathematica или в python), найти решение системы $Ax=b$ с помощью метода Гаусса.
2. Преобразовать систему $Ax=b$ к виду $x=Bx+c$, удобному для итераций. Проверить выполнение достаточного
условия сходимости итерационных методов $||B||_{\inf}<1$.
3. Написать программу, решающую систему линейных уравнений с помощью метода Зейделя, выполнить 10 итераций по методу Зейделя; взять любое начальное приближение. Предварительно проверить условие сходимости для метода Зейделя. Принимая решение, полученное в п. 1 за точное, найти величину абсолютной
погрешности итерационного решения (использовать норму $|| \times ||_{\inf}$).
4. Взять другое начальное приближение. Объяснить полученные результаты.

In [2]:
A = np.array([[29.7, 2., 0., 19.8, 2.],
              [9.9, -21., 0., -9.9, 1.],
              [-9.9, 11., 29., 6.6, 1.],
              [9.9, 7.5, 2., -19.8, 0.],
              [-49.5, -1., 23., 9.9, 84.],
             ])
b = np.array([26.2, -41.1, 97.4, 99.8, 27.1])

#### Найдем решение системы встроенным методом

In [3]:
x_solve1 = np.linalg.solve(A, b)
for i in range(len(x_solve1)):
    print("x",i+1,' = ', x_solve1[i],sep='')

x1 = 2.02020202020202
x2 = 4.0
x3 = 3.0
x4 = -2.212121212121212
x5 = 0.9999999999999998


#### Привдем $𝐴𝑥=𝑏$ к виду  $𝑥=𝐵𝑥+𝑐$

In [4]:
B = np.zeros_like(A)
c = np.zeros_like(b)

for i in range(len(B)):
    for j in range(len(B)):
        if i != j:
            B[i][j] = -A[i][j]/A[i][i]
    c[i] = b[i]/A[i][i]
print(B)
print()
print(c)

[[ 0.         -0.06734007 -0.         -0.66666667 -0.06734007]
 [ 0.47142857  0.          0.         -0.47142857  0.04761905]
 [ 0.34137931 -0.37931034  0.         -0.22758621 -0.03448276]
 [ 0.5         0.37878788  0.1010101   0.          0.        ]
 [ 0.58928571  0.01190476 -0.27380952 -0.11785714  0.        ]]

[ 0.88215488  1.95714286  3.35862069 -5.04040404  0.32261905]


Проверим сходимость

In [5]:
np.linalg.norm(B, np.inf)

0.9928571428571429

Меньше 1, значит метод Зейделя сходится

### Методо Зейделя

In [6]:
def zeidel(B, c, it, x0):
    n = len(B)
    B1 = np.tri(n)*B
    B2 = (np.tri(n).T)*B
    for i in range(it):
        xk = B@x0 +c
        x0 = B1@xk + B2@xk + c
    return xk

In [7]:
x0=[0.,0.,0.,0.,0.]
x_z = zeidel(B, c, 10, x0=x0)
print('Решение при приближении:', x0)
for i in range(len(x_z)):
    print("x",i+1,' = ', x_z[i],sep='')
abs_err = np.linalg.norm(x_z - x_solve1, np.inf)
print('Абсолютная погрешность: ', abs_err)

Решение при приближении: [0.0, 0.0, 0.0, 0.0, 0.0]
x1 = 2.0554503936000508
x2 = 4.006128899119399
x3 = 3.0209031690980166
x4 = -2.2478433086023597
x5 = 0.9942856693830833
Абсолютная погрешность:  0.03572209648114777


### Другое приближени

In [8]:
x0=np.array([0.1,0.1,0.1,0.1,0.1])*30
x_z = zeidel(B, c, 10, x0=x0)
print('Решение при приближении:', x0)
for i in range(len(x_z)):
    print("x",i+1,' = ', x_z[i],sep='')
abs_err = np.linalg.norm(x_z - x_solve1, np.inf)
print('Абсолютная погрешность: ', abs_err)

Решение при приближении: [3. 3. 3. 3. 3.]
x1 = 2.0078195936953502
x2 = 3.9595391785567595
x3 = 2.9874756441687884
x4 = -2.260448952073573
x5 = 0.9714301935750191
Абсолютная погрешность:  0.04832773995236117


In [9]:
x0=x_solve1
x_z = zeidel(B, c, 10, x0=x0)
print('Решение при приближении:', x0)
for i in range(len(x_z)):
    print("x",i+1,' = ', x_z[i],sep='')
abs_err = np.linalg.norm(x_z - x_solve1, np.inf)
print('Абсолютная погрешность: ', abs_err)

Решение при приближении: [ 2.02020202  4.          3.         -2.21212121  1.        ]
x1 = 2.0202020202020203
x2 = 4.0
x3 = 3.0000000000000004
x4 = -2.2121212121212115
x5 = 1.0
Абсолютная погрешность:  4.440892098500626e-16


При отдалении начального приближения от истинного корня, погрешность метода Зейделя растет

### Задача 5.2

Для системы уравнений Ax=b из задачи 5.1 найти решение по методу Зейделя с точностью
$\epsilon=10^{-6}$ , взяв любое начальное приближение. Для этого модифицировать программу из пункта 3 так, чтобы решение вычислялось с заданной точностью $\epsilon$. Предусмотреть подсчет количества итераций, потребовавшихся для достижения точности $\epsilon$.

In [10]:
def zeidel_tol(B, c, tol=1e-6, it=100, x0=[0.,0.,0.,0.,0.]):
    n = len(B)
    B1 = np.tri(n)*B
    B2 = (np.tri(n).T)*B
    iterations = 0
    x0 = np.ones(n)
    xk = np.copy(x0)
    while True: 
        iterations+=1
        xk = B@x0 +c
        x0 = B1@xk + B2@xk + c
        if iterations > it:
            print(f"Превышено ограничение на количество итераций ({it})")
            return xk,it
        if (np.linalg.norm(x0 - xk, np.inf) < tol):
            return xk,iterations
    return xk,iterations

In [11]:
tol=1e-6
x_z, iters = zeidel_tol(B, c, tol=tol)
print('Решение с погрешностью:',tol)
for i in range(len(x_z)):
    print("x",i+1,' = ', x_z[i],sep='')
print('Колво итераций',iters)
print()
abs_err = np.linalg.norm(x_z - x_solve1, np.inf)
print('Абсолютная погрешность: ', abs_err)

Решение с погрешностью: 1e-06
x1 = 2.020202642502103
x2 = 4.000000471391669
x3 = 3.0000004181619846
x4 = -2.2121212656274323
x5 = 1.0000001890107093
Колво итераций 34

Абсолютная погрешность:  6.223000830196668e-07


### Задача 5.7.1

Дана система уравнений $Ax=b$, где A – симметричная положительно определенная матрица
размерности $n х n$. Найти решение системы с точностью $\epsilon=10^{-6}$ с помощью метода простой итерации с оптимальным выбором итерационного параметра, а также с помощью метода, указанного в индивидуальном варианте. (Для метода релаксации обосновать выбор параметра релаксации w.) Сравнить скорость сходимости методов.

УКАЗАНИЕ. 

При проверке необходимого и достаточного условия сходимости итерационных методов для нахождения собственных значений матриц воспользоваться встроенной функцией eigenvals(M) пакета MATHCAD (либо другой встроенной функцией в wolfram mathematica или в python), возвращающей собственные значения матрицы M.

$$n = 20$$

$$m = 1$$

$$Доп. метод - Зейделя$$

#### Зададим матрицу

In [12]:
n = 20
m = 1

In [13]:
A1 = np.zeros((n, n))
b1 = np.zeros(n)

q = 0.993 + ((-1)**m)* m * 10**(-4)
tetta = sum([q**(2*i) for i in range(1, n+1)])
tm = (m + n)
for i in range(n):
    b1[i] = tm * (q)**i
    for j in range(n):
        if i==j:
            A1[i, j] = tetta + 2*(q**i)*tm + (tm)**2
        else:
            A1[i, j] = tetta + (q**i + q**j)*tm
print(A1)
print()
print(b1)

[[500.27869748  59.12959748  58.98155609  58.8345658   58.68861913
   58.54370869  58.39982711  58.25696709  58.11512138  57.97428277
   57.83444411  57.69559831  57.55773831  57.42085712  57.28494779
   57.15000341  57.01601714  56.88298217  56.75089175  56.61973917]
 [ 59.12959748 499.98049748  58.83245609  58.6854658   58.53951913
   58.39460869  58.25072711  58.10786709  57.96602138  57.82518277
   57.68534411  57.54649831  57.40863831  57.27175712  57.13584779
   57.00090341  56.86691714  56.73388217  56.60179175  56.47063917]
 [ 58.98155609  58.83245609 499.6844147   58.53742441  58.39147774
   58.2465673   58.10268572  57.9598257   57.81797999  57.67714138
   57.53730272  57.39845692  57.26059692  57.12371573  56.9878064
   56.85286202  56.71887575  56.58584078  56.45375036  56.32259778]
 [ 58.8345658   58.6854658   58.53742441 499.39043411  58.24448745
   58.099577    57.95569542  57.8128354   57.67098969  57.53015108
   57.39031242  57.25146662  57.11360663  56.97672544  56.84

In [14]:
B1 = np.zeros_like(A1)
c1 = np.zeros_like(b1)

for i in range(len(B1)):
    for j in range(len(B1)):
        if i != j:
            B1[i][j] = -A1[i][j]/A1[i][i]
    c1[i] = b1[i]/A1[i][i]
print(B1)
print()
print(c1)

[[ 0.         -0.11819331 -0.1178974  -0.11760358 -0.11731185 -0.11702219
  -0.11673459 -0.11644903 -0.11616549 -0.11588397 -0.11560445 -0.11532691
  -0.11505135 -0.11477774 -0.11450607 -0.11423633 -0.11396851 -0.11370259
  -0.11343855 -0.11317639]
 [-0.11826381  0.         -0.1176695  -0.11737551 -0.11708361 -0.11679377
  -0.116506   -0.11622027 -0.11593656 -0.11565488 -0.11537519 -0.11509749
  -0.11482176 -0.11454798 -0.11427615 -0.11400625 -0.11373827 -0.11347219
  -0.113208   -0.11294568]
 [-0.11803761 -0.11773923  0.         -0.11714879 -0.11685671 -0.11656671
  -0.11627876 -0.11599286 -0.11570899 -0.11542714 -0.11514728 -0.11486942
  -0.11459352 -0.11431959 -0.1140476  -0.11377754 -0.1135094  -0.11324316
  -0.11297881 -0.11271634]
 [-0.11781276 -0.1175142  -0.11721775  0.         -0.11663116 -0.11634099
  -0.11605287 -0.11576681 -0.11548277 -0.11520075 -0.11492073 -0.1146427
  -0.11436664 -0.11409254 -0.11382039 -0.11355018 -0.11328188 -0.11301548
  -0.11275098 -0.11248835]
 [-0.

In [15]:
x_solve2 = np.linalg.solve(A1, b1)
x_solve2

array([0.01478947, 0.01453576, 0.01428385, 0.01403372, 0.01378537,
       0.01353879, 0.01329395, 0.01305086, 0.01280949, 0.01256983,
       0.01233187, 0.01209561, 0.01186102, 0.0116281 , 0.01139683,
       0.0111672 , 0.01093921, 0.01071283, 0.01048806, 0.01026488])

In [16]:
np.linalg.norm(B1, np.inf)

2.197050304894725

Для этой матрицы метод расходится

In [17]:
def iters_method(B, c, tol):
    n = len(B) #размерность
    print(n)
    xk = np.ones(n)
    xk1 = np.copy(xk)
    iters = 0
    while True: 
        xk1 = B@xk +c
        iters += 1
        if iters > 1000:
            print(f"Превышено ограничение на количество итераций ({iters})")
            return xk,iters
        if (np.linalg.norm(xk - xk1, np.inf) < tol):
            return xk,iters
        xk = xk1
    return xk, iters

In [18]:
B_test = B
c_test = c
x_solve = x_solve1

In [19]:
tol=1e-6
x_z, iters = iters_method(B_test, c_test, tol=tol)
print('Решение с погрешностью:',tol)
for i in range(len(x_z)):
    print("x",i+1,' = ', x_z[i],sep='')
print('Колво итераций',iters)
print()
abs_err = np.linalg.norm(x_z - x_solve, np.inf)
print('Абсолютная погрешность: ', abs_err)

5
Решение с погрешностью: 1e-06
x1 = 2.0202022006151656
x2 = 3.999999607360686
x3 = 3.00000004964077
x4 = -2.2121220687702934
x5 = 0.9999996323089921
Колво итераций 67

Абсолютная погрешность:  8.566490814487793e-07


Для примера работы была взята матрица из предыдущего задания.

In [20]:
tol=1e-6
x_z, iters = zeidel_tol(B_test, c_test, tol=tol,it=200)
print('Решение с погрешностью:',tol)
for i in range(len(x_z)):
    print("x",i+1,' = ', x_z[i],sep='')
print('Колво итераций',iters)
print()
abs_err = np.linalg.norm(x_z - x_solve, np.inf)
print('Абсолютная погрешность: ', abs_err)

Решение с погрешностью: 1e-06
x1 = 2.020202642502103
x2 = 4.000000471391669
x3 = 3.0000004181619846
x4 = -2.2121212656274323
x5 = 1.0000001890107093
Колво итераций 34

Абсолютная погрешность:  6.223000830196668e-07


Видно, что метод Зейделя сходится быстрее